### ISSUE TITLE
Set up automated deployment

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform-api#115]

**Comment by alexwlchan** [comment]
Some thoughts over lunchtime, I think we have two options:

1. We give Travis the permissions to do a targeted `terraform plan` and `terraform apply`. Once a job on master completes, it deploys the new application. An easy extension of what we already have, but means giving more permissions to an external service.
2. Travis pushes a release ID file to S3. Watch the file with a Lambda trigger, when it changes have that pull the existing task definition, then push a new task definition/service update to ECS. Less permissions outside AWS, but risk of it falling over if there are timeout errors. I think Terraform will handle it smoothly, but don't know for sure.

**Comment by alexwlchan** [comment]
Right now, Travis builds our images and pushes them to ECR. The only thing it doesn’t do is create the task definition.

We have a Lambda that watches an S3 file and creates new task definitions (https://github.com/wellcometrust/platform-infra/tree/master/lambdas/update_task_for_config_change) – writing another Lambda that does the same thing if the release ID file changes would be a fairly small extra step. I’m not sure how Terraform would react if it found the new task definition though, we’d need to experiment.

**Comment by kenoir** [comment]
Closing as done - as we're working without an explicit integration environment I think we've got as far as we need to for now.
