### ISSUE TITLE
Set up production Elasticsearch

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform-api#12]

**Comment by alfraser86** [comment]
@kenoir @alexwlchan are the settings for our hosted elastic cache held in code somewhere?

**Comment by kenoir** [comment]
@alfraser86 mappings are described here: https://github.com/wellcometrust/platform-api/issues/40

Settings like cluster size, memory, etc, are not. Elastic Cloud does not have an API for provisioning clusters (as far as I know) so it is not possible to describe the setup in code.
