### ISSUE TITLE
Set up autoscaling groups using Terraform

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform-api#13]

**Comment by kenoir** [comment]
This is required for stable and graceful updates of production infra when instance launch configurations change.

**Comment by alexwlchan** [comment]
Copying my notes from @kenoir’s explanation:

We have auto-scaling groups of EC2 instances, which are defined by Terraform. ECS will push tasks to those instances, which is something like our app or our Jenkins config.

![terraform asgs](https://cloud.githubusercontent.com/assets/301220/22985244/d0f31942-f39f-11e6-8717-d1a3ad67235f.png)

If we want to change the launch configuration of the Terraform group (for example, changing from t2.micro to t2.small), we update the Terraform plan and run `terraform apply`. Unfortunately, the way ASGs work mean that this launch configuration isn’t apply to running instances – it only applies when a new instance is launched. Something to do with ASGs being based on CloudFormation.

We could go in and terminate existing instances, then wait for the ASG to bring them up with the new launch configuration – but this can cause outages. We want our ASGs to gracefully update with new launch configuration.

**Comment by kenoir** [comment]
Addressed by https://github.com/wellcometrust/platform-infra/pull/8
