### ISSUE TITLE
Define core fields for works

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform-api#130]
These are the fields that are always returned on a work, in responses that don't have includes.

They should be the fields always required to e.g. link to a work.

**Comment by pollecuttn** [comment]
@ChristopherHilton to list core fields here before closing this issue

**Comment by ChristopherHilton** [comment]
First pass at the absolutely core fields to be present in all works:

Identifier
Label
Description
Creator
CreatedDate

(may not all be populated)

**Comment by alexwlchan** [comment]
I don't remember why I assigned this to myself, but all these fields are now present in the API, so I think we can close this.

```console
$ curl 'https://api.wellcomecollection.org/catalogue/v0/works/a8jf3u38' | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   270  100   270    0     0   1765      0 --:--:-- --:--:-- --:--:--  1764
{
  "@context": "https://api.wellcomecollection.org/catalogue/v0/context.json",
  "id": "a8jf3u38",
  "label": "Charles Babbage. Wood engraving, 1871.",
  "description": "Charles Babbage. Wood engraving, 1871.",
  "createdDate": {
    "label": "1871",
    "type": "Period"
  },
  "creators": [],
  "type": "Work"
}
```

🎉
