### ISSUE TITLE
Speed up docker image creation

### ISSUE THREAD

**Issue by alicefuzier** [wellcometrust/platform-api#175]
Currently our builds take a long time and most of that time is being spent in creating the docker image. We should investigate if we can optimize it so that it takes less time

**Comment by alexwlchan** [comment]
[Latest build](https://travis-ci.org/wellcometrust/platform-api/builds/224362899) took 9 minutes for a complete set; no more than 5½ minutes to get an individual rebuild. I reckon that’s fast enough for now.

**Comment by kenoir** [comment]
Wow. Good work.
