### ISSUE TITLE
Properly version deployed assets

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform-api#18]

**Comment by alexwlchan** [comment]
Currently the `sbt ecr:push` ([circle.yml L36](https://github.com/wellcometrust/platformprototype/blob/master/circle.yml#L36)) command will push to the "latest" label/tag in ECR.

Really it should push to a label matching the version in `build.sbt`.

**Comment by alexwlchan** [comment]
We’re already creating tagged images: for example, this is what I have locally:

```console
$ docker images | grep wellcome/platform | awk '{print $2}'
v0.1.2-SNAPSHOT
v0.1.1-SNAPSHOT
latest
```

But if I do an `ecr:push`, I don’t see it showing up – it could be that it’s only pushing `latest`, but I don’t think that would explain why new Circle builds (which don’t have old images lying around) aren’t pushing images with a non-latest tag.

**Comment by kenoir** [comment]
Suspect the following change might work:

https://github.com/wellcometrust/platformprototype/blob/master/platform-api/build.sbt#L94: 

```scala
// repositoryName   in ecr := name.value
// Try this instead:
repositoryName   in ecr := s"${name.value}:${version.value}"
```

**Comment by alexwlchan** [comment]
That was disappointingly simple, but it works.

**Comment by alexwlchan** [comment]
This was based on the old version of the application and it works, doing this for the Finatra stuff is a separate task.

**Comment by kenoir** [comment]
Current project makes use of https://github.com/sbt/sbt-git to version assets.
