### ISSUE TITLE
Find a way to re-send data in DynamoDB to the transformer

### ISSUE THREAD

**Issue by alicefuzier** [wellcometrust/platform-api#194]
Currently the transformer reads data to be transformed form a DynamoDB stream. The DynamoDB stream only contains information about updates to a table so, if a stream record has been already processed once or has been in the stream for some time without being processed, it is not visible for the transformer anymore.

Since our datamodel is likely to change often, it is likely that we will need to re-send items in the Dynamo tables through the pipeline. 
Currently the only way to do that is to delete the items from the DynamoDB table and insert them again. We need a simpler process to do that.

Possible idea: a lambda that turns up the table write capacity, marks each record in the table as updated and turns the capacity back down?

**Comment by alexwlchan** [comment]
> a lambda that turns up the table write capacity, marks each record in the table as updated and turns the capacity back down?

One risk with a Lambda is that we hit the 5 minute timeout.

I’m going to argue for this to be a locally-run Python script, because we shouldn't be doing it very often. 😉

**Comment by alicefuzier** [comment]
I get the lambda thing, but I don't think it should be a locally run script. I think we will have to do it often enough to have a proper space in our pipeline/infrastructure.

**Comment by alexwlchan** [comment]
This doesn’t actually work, but it’s an idea I was semi-keen on before scrapping.

---

Here’s a straw man design for my current thinking:

![transformer_schema](https://cloud.githubusercontent.com/assets/301220/26006828/d3062fa6-3735-11e7-912f-88f0542c3c07.png)

We add a new hash key to the DynamoDB tables: _schemaVersion_.

Within the transformer, _schemaVersion_ is a hard-coded number that we increment every time we change the internal transformation (whether through config flags or something else, I don’t really mind). Increments independently for different data sources (Calm, Miro, etc.).

When the transformer posts to the ID minter topic, it includes:

* the current data
* the name of the source table
* the transformer's schema version

We then subscribe a Lambda to the topic, which is responsible for updating the schema version in the table.

…which then causes any update to the table to trigger an infinite stream of updates, er, oops. 😆

**Comment by alexwlchan** [comment]
In fact, anything that involves updating something in the table will surely trigger an infinite cycle of updates? 🤔

**Comment by kenoir** [comment]
Interesting. I'm not sure that the infinite loop you suggest is inevitable (obviously there needs to be a check somewhere to avoid it). I'd like the transformer not to be involved in making requests to dynamo if possible. 

I think the version update via SNS topic you describe is spot on.

**Comment by alexwlchan** [comment]
> I'm not sure that the infinite loop you suggest is inevitable (obviously there needs to be a check somewhere to avoid it).

I think it’s a case of “pick two”:

1. Keep schema version info in the same table as the data
2. Only record a change in transformed schema version after the transform succeeds
3. Don't trigger a second event on the table stream for the schema version when you update a record in the table

Giving up (1) seems like a recipe for a headache. Of the remaining two, I think (2) offers us more benefits than (3).

> I'd like the transformer not to be involved in making requests to dynamo if possible.

I'm not sure I understand what you mean? It already has the event stream, but I don't think I’m suggesting any additional transformer/DynamoDB interactions.

**Comment by kenoir** [comment]
"any additional transformer/DynamoDB interactions."

> For reindexing, add a POST endpoint to the transformer that asks the table for all records < current schema version.

We get which fields were modified in the stream event. We can simply discard events that modify the schema version.

**Comment by kenoir** [comment]
... or indeed discard updates that match the current schema version. 

We need to whiteboard all these ideas in person!

**Comment by alexwlchan** [comment]
Just to note the design we agreed in the whiteboard on Monday (new parts in orange):

![reindexer](https://cloud.githubusercontent.com/assets/301220/26199289/591e20b4-3bc1-11e7-9bb8-9cee99ddd5e4.png)

* [ ] We have an external "schema version" for each data source, which records the version of our transformer. This starts at 1 and gets bumped every time we change the way the transformer works _or_ want to reindex.
* [ ] We add a new range key to our DynamoDB table "schema version". When the adapter initially adds a record, it uses the current schema version. (This is really _what version of the transformer will we try to transform this record with_.)
* [ ] We add a new **reindexer** application. This is triggered on-demand, and when it runs, it proceeds to update every row in the table to the current schema version.
* [ ] This triggers a table update, which adds an event on the event stream, and the transformer picks it up as previously.

**Comment by kenoir** [comment]
Related: 
- https://github.com/wellcometrust/platform-api/pull/353
- https://github.com/wellcometrust/platform-api/pull/346
- https://github.com/wellcometrust/platform-api/pull/348
- https://github.com/wellcometrust/platform-api/pull/345
- https://github.com/wellcometrust/platform-api/pull/315
