### ISSUE TITLE
Tech debt: be consistent in our use of flags

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform-api#206]
Spotted while reviewing #197.

We currently have two ways of defining flags in our `Server` class:

1. Defining them as a variable on the class:

    ```scala
    private final val apiName =
         flag(name = "api.name", default = "catalogue", help = "API name path part")
    ```

2. Calling `flag[String]` like so:

    ```scala
    flag[String]("es.index", "records", "ES index name")
    ```

These then come in through DI, although I see some with `@Flag` and some not.

We should pick an approach, use that for future code, and change our existing code to match.

**Comment by jtweed** [comment]
I agree we should consistently use typing and named parameters or not, but otherwise these two things are the same. It's just that in the first case, we're assigning the flag to a local variable so that we can then use it in the class where it's defined.
