### ISSUE TITLE
What should our versioning policy be?

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform-api#207]
Currently all our containers are tagged “0.0.1”. Now we are actually starting to produce a semi-stable API, do we need to rethink this? At least to make our containers easier to identify in a list?

How about (for now) `0.x.0`, where we increment `x` for changes to the unified item and/or API?

**Comment by kenoir** [comment]
http://semver.org/

**Comment by kenoir** [comment]
With the commit hash appended for things that don't fit the semver model.

**Comment by kenoir** [comment]
Closing as resolved.
