### ISSUE TITLE
Add pagination to the API

### ISSUE THREAD

**Issue by alicefuzier** [wellcometrust/platform-api#216]
Add pagination functionality so that we can see items past the first page. Look at using [scroll](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html) for consistent ordering of items

**Comment by kenoir** [comment]
Some work in https://github.com/wellcometrust/platform-api/issues/216 to make this easier.

**Comment by alexwlchan** [comment]
Resolved by #275.
