### ISSUE TITLE
Tests in CI are flakey

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform-api#246]
On a fairly regular basis, I’m seeing Travis fail one of the container-based tests, but the failure clears up on a restart:

https://travis-ci.org/wellcometrust/platform-api/jobs/229136374
https://travis-ci.org/wellcometrust/platform-api/jobs/229136371

Tests should fail reliably.

**Comment by kenoir** [comment]
Tests must be reliable. This is high priority I reckon.

**Comment by alexwlchan** [comment]
Another flakey log in build 340: https://travis-ci.org/wellcometrust/platform-api/builds/229664810

[travis_api_log.txt](https://github.com/wellcometrust/platform-api/files/982804/travis_api_log.txt)

**Comment by alexwlchan** [comment]
I’ve had to restart a job four times for my latest PR. 😞 

I wonder if we're getting squeezed by Travis when the builds are busy, and our tests expect a bit too much performance?

**Comment by alicefuzier** [comment]
Hopefully it's fixed. We can reopen it if we find some more flakey tests
