### ISSUE TITLE
Add support for ingestor writing to separate Elasticsearch indices

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform-api#250]
Right now the ingestor takes a single flag `es.index`, and writes everything it receives into that index.

We'll have multiple LD types (work, item, agent, etc.), and each will need to be stored in its own index. We should enhance the ingestor to support writing different items to different indices.

As part of this, we should rename the current "items" index to "works", per #234.

**Comment by kenoir** [comment]
Closing as done.
