### ISSUE TITLE
Regular ingest of data from CALM

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform-api#28]

**Comment by alexwlchan** [comment]
[AWLC] Breakdown:

- [ ] Write a script that does a one-shot push of Calm data into DynamoDB
- [ ] Handle incremental updates (Calm records include a DateUpdated field, so we don’t require too much machinery for this)

We already have part of (1) from the prototype – we may be able to adapt this.

Related: #22, #20, #11.

**Comment by alexwlchan** [comment]
Superseded by #52, #53, #54 and #55.
