### ISSUE TITLE
Only ingest data for V collection images

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/platform-api#308]
- [x] Remove everything from Dynamo DB and Elasticsearch
- [x] Amend adapter to only ingest V
- [x] Ingest V collection

**Comment by pollecuttn** [comment]
- Remove everything from Dynamo DB and Elasticsearch
- Amend adapter to only ingest V
- Ingest V collection

**Comment by alexwlchan** [comment]
Elasticsearch is currently empty, and I just flushed the DynamoDB table.

**Comment by alexwlchan** [comment]
I’m currently running the adapter over the V images.

**Comment by alexwlchan** [comment]
V collection results are showing up in the API.

**Comment by jtweed** [comment]
We should keep this open until all V images have ingested correctly.

I believe there should be 62,948.

**Comment by alexwlchan** [comment]
Now we filter out images that don't have (copyright) clearance, break down as follows:

* 52,312 images in the API
* 9,750 images don't have clearance

886 images unaccounted for.

**Comment by alexwlchan** [comment]
We’re missing quite a few images in DynamoDB – approx. 62,048, vs the 62,948 we actually expect.

I’m going to try re-running the adapter.

**Comment by alexwlchan** [comment]
53,198 images in the API. 🎉 

Combined with the 9,750 images that don’t have the appropriate clearance, that’s 62,958 – exactly the number we expect.

**Comment by jtweed** [comment]
Great. Do we know why the adapter failed to ingest some of those previously?

**Comment by alexwlchan** [comment]
> Do we know why the adapter failed to ingest some of those previously?

Leftover change from a previous run. All the unadapted records were in a sequence at the start of the XML dump – V00001, V00002, ….

A week or so ago, I was running the adapter in batches, 1000 records at a time. To speed things up, I had a local change to skip certain records:

```python
for idx, record in enumerate(miro_records):
    if idx < N:
        continue
```

where `N` was the records I’d already adapted.

When we dropped the table and I re-ran the adapter, I forgot to remove this patch.
