### ISSUE TITLE
Create Elasticsearch mapping

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform-api#40]

**Comment by alexwlchan** [comment]
I’ve got a spreadsheet of fields in the Calm records from @ChristopherHilton. This has a description of each field, and a Y/N of whether we expose that field to the public. I’ve added a Y/N for whether a field should be searchable, and shared it in Slack for an initial review.

I’ve also written a skeleton Python script that builds the index in Elasticsearch for us, based on sensible guesses of what a field type should look like. I’ve got part of the glue code DynamoDB ~> Elasticsearch working, and tying it down depends on what mapping we go with.

**Comment by kenoir** [comment]
See:
- https://github.com/wellcometrust/platform-api/blob/master/calm-ingest/mapping_collection.py
- https://github.com/wellcometrust/platform-api/blob/master/calm-ingest/mapping_component.py
