### ISSUE TITLE
Rename "API" API to "Catalogue" API

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform-api#41]

**Comment by jtweed** [comment]
The initial API that we've been building for searching metadata will be called the Catalogue API.

It should have the following base URL:

https://api.wellcomecollection.org/:version/catalogue

Where :version is currently v0.

For clarity, we should rename the project now, before we create additional APIs for IIIF, asset management etc.

**Comment by alexwlchan** [comment]
So this repo should be named “platform-catalogue”? Or just “catalogue”? Or “catalogue-api”?

**Comment by jtweed** [comment]
I would have thought the answer to that depends on #61.

**Comment by kenoir** [comment]
@jtweed i've got a plan for this, but I think it's a good idea to talk about it in person.
