### ISSUE TITLE
Add pagination links to the API

### ISSUE THREAD

**Issue by pollecuttn** [wellcometrust/platform-api#453]
Add `next` and `prev` links to paginated API responses.

`GET https://localhost:8888/$apiPrefix/works?page=2`

```json
{
  "@context": "https://localhost:8888/$apiPrefix/context.json",
  "type": "ResultList",
  "pageSize": 1,
  "totalPages": 3,
  "totalResults": 3,
  "prev": "https://localhost:8888/$apiPrefix/works?page=1&pageSize=1",
  "next": "https://localhost:8888/$apiPrefix/works?page=3&pageSize=1",
  "..."
}
```

**Comment by jamesgorrie** [comment]
We do have pagination no?
https://next.wellcomecollection.org/search?page=2&query=gun

**Comment by pollecuttn** [comment]
Ah - so have I got the wrong end of the stick of what was mentioned in stand up yesterday about needing pagination? What did I get wrong?

**Comment by kenoir** [comment]
Links!

**Comment by jamesgorrie** [comment]
Potentially, we already have it and it works.

**Comment by kenoir** [comment]
The API result will likely have a `next` param that provides a link to the next page of results.

**Comment by jamesgorrie** [comment]
Ah - okay, that's not for @gestchild and @davidpmccormick to flesh out.
I can update the issue.

**Comment by jamesgorrie** [comment]
Sorry @pollecuttn for the misunderstanding.

**Comment by alexwlchan** [comment]
My understanding was that the pagination would look something like this:

```console
curl https://api.wellcomecollection.org/v0/catalogue/works?page=2
{
    ...
    "next": "https://api.wellcomecollection.org/v0/catalogue/works?page=3",
    "prev": "https://api.wellcomecollection.org/v0/catalogue/works"
}
```

so downstream clients don't need to copy the logic for manipulating the query string.

**Comment by kenoir** [comment]
Like this: 
```json
{
  "@context": "https://localhost:8888/$apiPrefix/context.json",
  "type": "ResultList",
  "pageSize": 1,
  "totalPages": 3,
  "totalResults": 3,
  "next": "https://localhost:8888/$apiPrefix/works?page=3&pageSize=1",
  "..."
}
```

**Comment by jamesgorrie** [comment]
@kenoir not in a `links` property?

**Comment by kenoir** [comment]
@jamesgorrie TBD.

**Comment by jamesgorrie** [comment]
@kenoir @alexwlchan  I was having a think about this, and wondered why we aren't using tokens?

The reason I ask is that responses aren't immutable in this fashion, especially when results are ordered reverse chronologically (RC.

e.g.
* I browse RC, page 5 of my results has everything I was looking for - I send that to my colleague
* They look at it a week later where we've digitised a million other things related to that search, they are now staring at results that don't make sense and I lose my job.

Here's a small article (not my favourite, but it makes sense):
http://blog.vermorel.com/journal/2015/5/8/nearly-all-web-apis-get-paging-wrong.html
