### ISSUE TITLE
Modify Transformer to use SQS (Standardise service event streams)

### ISSUE THREAD

**Issue by alicefuzier** [wellcometrust/platform-api#478]
The transformer reads the dynamo stream and publishes to an SNS topic. This is different from how the id minter and the ingestor work, in that their input is an SQS queue. 

This has some advantages, for example the fact that we have dead letter queues and alarms for each dead letter queue already provisioned in terraform. Having the transformer behave the same way would give us more information when investigating a failure and would avoid loosing the item which failed, so that we can easily resend it.

So, we should push the logic of parsing the dynamo db stream out into a lambda that then pushes to an SNS topic and into a SQS queue, which would be the input of the transformer

**Comment by kenoir** [comment]
Done and deployed - some errors, will be fixed by https://github.com/wellcometrust/platform-api/issues/675.
