### ISSUE TITLE
Create library to do updates from Calm to DynamoDB

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform-api#53]
Our current script takes an XML export from Calm and shoves the whole thing into a new DynamoDB table.

We should use the Calm API to process updates (possibly using the “Modified” field) to update an existing DynamoDB table with new data.

This task only covers the “update existing data” part. Related: #52.

**Comment by kenoir** [comment]
We should probably be able to do both.

**Comment by alexwlchan** [comment]
Closed by #80.
