### ISSUE TITLE
Loris deployment using docker

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform-api#536]

**Comment by alexwlchan** [comment]
What else do we need to do for this?

**Comment by kenoir** [comment]
Pinging @alexwlchan @jtweed is this done?

**Comment by alexwlchan** [comment]
At some point we might want a way to build from other-than-last-released-version-of-Loris, but that can be a separate ticket, and depends a bit on where we put our Loris fork. I’m happy to close for now.
