### ISSUE TITLE
Create application to do updates from DynamoDB to ES

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform-api#55]
As we push new data into Calm, that will appear as new rows in DynamoDB. Our application needs to read these updates, and add them to our Elasticsearch index with the current mapping.

This task covers incremental updates after the initial ingest. Related: #54.

**Comment by kenoir** [comment]
Closing as this is split to:

https://github.com/wellcometrust/platform-api/issues/68
https://github.com/wellcometrust/platform-api/issues/54
