### ISSUE TITLE
Add items to Catalogue API

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform-api#572]
Add a list of `items` to works. Items are identified objects in their own right and need to have IDs assigned by the ID minter.

`items` should be an include on works in the API.

Right now, they have no additional metadata for Miro data (they will for other sources), but we need to add them so we can properly link to the images.

See: https://github.com/wellcometrust/platform-api/blob/master/ontologies/Examples/MIRO_sample_image_of_artwork_v2.json

**Comment by alexwlchan** [comment]
> `items` should be an include on works in the API.

They’re appearing in the staging API, but not as an include. I’ll fix that now.

**Comment by alexwlchan** [comment]
The prod API now has (unidentified) items, so I’ve opened #876 to track putting IDs on there. We can then manage that separately.
