### ISSUE TITLE
Add links to image assets in Catalogue API

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform-api#574]
Add `locations` to `Item`s in the API.

Initially for Miro data, we will have a single `locationType` of `iiif-image`, but this will be extended in the future to include other location types for the other data sources, including physical shelf locations.

Locations also have license info, which should be set for Miro data to the same license as the `thumbnail` on the associated work.

See: https://github.com/wellcometrust/platform-api/blob/master/ontologies/Examples/MIRO_sample_image_of_artwork_v2.json

**Comment by alexwlchan** [comment]
The items in the API have a `locations` field with a `locationType` of `iiif-image`. What else are we doing on this (in the immediate future, at least)?

https://api.wellcomecollection.org/catalogue/v0/works?includes=items

**Comment by alexwlchan** [comment]
Last piece to do here is tracked by #467.
