### ISSUE TITLE
Tidy up the scripts for multi-project builds in Circle

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform-api#63]
We merged some fairly simple scripts as part of #62. They work, but they need tidying up:

* [x] Make it easier to add new projects
* [x] Comments
* [x] Only build parts of the project that have changed

**Comment by alexwlchan** [comment]
Thinking a bit more about skipped builds: because Circle may build several commits at once (e.g. if you’ve just pushed a rebased branch), I think we should take the following approach:

* If the branch is master, always build everything. This shouldn’t be blocking anything, so the extra time for a full build doesn’t block somebody.
* If it’s a branch/pull request, build based on the diff from master.

^^That sound sensible @kenoir?

**Comment by kenoir** [comment]
Sounds fine. I think ultimately we will want to move to a CI that supports build pipelines explicitly, but this is a pretty good solution for now.
