### ISSUE TITLE
Set up a cache cleaning service for EFS

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform-api#656]
Related to #655.

Once we have Loris caching masters to EFS, we need to keep the cache relatively tidy to avoid running up big costs. We should create a service that cleans our EFS mounts for us. These scripts from the Loris repo are probably a good start:

https://github.com/loris-imageserver/loris/blob/development/bin/loris-cache_clean.sh
https://github.com/loris-imageserver/loris/blob/development/bin/loris-http_cache_clean.sh

**Comment by alexwlchan** [comment]
We’re going to pair on this tomorrow.

**Comment by alexwlchan** [comment]
Still to do on this: set up a scheduled task, which is blocked on https://github.com/terraform-providers/terraform-provider-aws/pull/977 being released.

**Comment by alexwlchan** [comment]
(Terraform 1.10 is in RC1, so I assume this is imminent – I don’t think it’s worth writing this as a Lambda just to throw it away days later.)

**Comment by kenoir** [comment]
Have manually added this as a scheduled task. We'll remove them when the next version of terraform is released.
