### ISSUE TITLE
Create worker to send post transform updates to Elasticsearch

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform-api#68]
Sits in front of ES, reading updates from an SQS queue before performing write operations.

This application will expect updates in the ES "unified" format and will not perform any transformations other than to convert to an ES readable format.

**Comment by kenoir** [comment]
@alexwlchan when you create new tickets for us to work on can you assign them to both of us so we get a notification?

**Comment by alexwlchan** [comment]
> can you assign them to both of us so we get a notification?

Sure. I didn’t realise you weren’t getting notifications (I’m subscribed to the repo updates).
