### ISSUE TITLE
L and V image size analysis

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform-api#742]
To help with selection of images, we need to output two CSV files that contain the following, one for L and one for V images:

filename,width,height,filesize

We can use `identify` (part of ImageMagick) to get the first three of those, the last will need to come from `ls`, as `identify` outputs a human readable file size that can't then be used for sorting.

This will output the first three parts from `identify`:

`identify -format "%f,%w,%h" $file`

**Comment by jtweed** [comment]
I think we should do this using AWS Batch, so that we can use it as a test case.

**Comment by alexwlchan** [comment]
Okay, so in fact we can do this without using Batch or even looking at the images themselves.

* The Miro XML exports include information about image dimensions
* The ListObjectsV2 API in S3 includes file sizes (you don't even need to call HeadObject!)

There’s a bit of extra cleaning to do – keys in S3 don’t precisely match IDs in Miro, but it’s pretty close. I’ve got a first pass of the code done, and I’ll tidy it up properly on Monday morning.

**Comment by alexwlchan** [comment]
The final CSVs are in our Dashboard S3 bucket and I’ve sent them to Christy. Assuming there aren’t any problems, I’ll close this issue.

**Comment by alexwlchan** [comment]
Closing as Christy seems happy so far. :D
