### ISSUE TITLE
Delete the Loris caches

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform-api#747]
AIUI, Loris has three caches:

* Cache of the full-size original files from S3, in case you want to redraw new derivatives
* Cache of the `info.json` files (small, probably not great for NFS performance)
* Cache of the derived image files served to users (which are already cached by CloudFront)

Right now Loris only has a binary `enable_caching` config option – it would be nice to disable the latter two and see if that improves performance. Will likely require upstream changes.

**Comment by alexwlchan** [comment]
Gatling tests showed that the EFS cache wasn’t helping performance – rescoping this ticket to track deleting that old config when we have a few more runs under our belts.

**Comment by alexwlchan** [comment]
Closed by #758.

**Comment by ewg118** [comment]
Apropos, where is the info.json cache stored? I did some apache configurations to change the URL pattern of Loris, but a few of the info.json files still contain the old URI.

**Comment by alexwlchan** [comment]
@ewg118 If you look in your Loris configuration, under `[img_info.InfoCache]`, it’s the `cache_dp` key.

For example:

https://github.com/wellcometrust/platform-api/blob/master/terraform/services/config/templates/loris.ini.template#L58-L59
