### ISSUE TITLE
Filter out images from the API that don’t have technical metadata

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform-api#759]
So we don’t have broken images showing up in the API.

**Comment by pollecuttn** [comment]
@alexwlchan Is this something the Experience team need to be aware of either because it helps them or in case they don't get the results they expect?

**Comment by alexwlchan** [comment]
Practical effect of this is that the API should have less broken images – no change required for the Experience team, but the signal-to-noise ratio of results should increase.

We’re planning to use technical metadata (e.g. image dimensions) as a proxy for “does this image exist?”.

**Comment by alexwlchan** [comment]
Resolved by #800, we’ve run a reindex and made this the prod API.
