### ISSUE TITLE
Broken images from image server

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/platform-api#767]
Issue to track broken images in /search and /works

**Broken thumbs on results:**
https://next.wellcomecollection.org/search?page=1&query=creators:James%20Gillray

**Broken image on work page:**
https://next.wellcomecollection.org/works/x6n7xy8m
https://next.wellcomecollection.org/works/qcxmcmwf
https://next.wellcomecollection.org/works/wjrukcp5
https://next.wellcomecollection.org/works/ycfmzffs
https://next.wellcomecollection.org/works/s5tsqh7x
https://next.wellcomecollection.org/works/p59cftrt
https://next.wellcomecollection.org/works/fkybrep7
https://next.wellcomecollection.org/works/wsxb9fkt
https://next.wellcomecollection.org/works/jgx43zvc
https://next.wellcomecollection.org/works/ycwsktsg

**Comment by alexwlchan** [comment]
Related: #759.

**Comment by alexwlchan** [comment]
Closing – all these works are now excluded from the Catalogue API as they don’t have associated image files, so these pages don’t show up in search pages.
