### ISSUE TITLE
Add thumbnail on works

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform-api#792]
Add a `thumbnail` **include** to works, that returns the URL of a thumbnail image and its associated licence.

The license data for Miro images should be ingested from `image_use_restrictions`. This _should_ be a valid CC licence for all V images, but there may be some messy edge cases that we'll need to work through.

```
{
  "type": "Work",
  ...
  "thumbnail": {
    "type": "Location",
    "locationType": "thumbnail-image",
    "url": "https://iiif.wellcomecollection.org/image/V0042826ER.jpg/full/300,/0/default.jpg",
    "license": {
      "type": "License",
      "licenseType": "CC-BY",
      "label": "Attribution 4.0 International (CC BY 4.0)",
      "url" : "http://creativecommons.org/licenses/by/4.0/"
    }
  }
}
```

**Comment by kenoir** [comment]
Add display type for license and location.

**Comment by kenoir** [comment]
Swagger docs too.

**Comment by alexwlchan** [comment]
Okay, I think all the work is done for this. We need to decide how we’re doing autogen and implement that, but after that the pieces should topple like dominos.

**Comment by alexwlchan** [comment]
Ah wait, I’d missed this was an include!

**Comment by alexwlchan** [comment]
These are now exposed in the prod API:

🎉 ✨
