### ISSUE TITLE
Add nginx container to service deployments by default.

### ISSUE THREAD

**Issue by kenoir** [wellcometrust/platform-api#86]
In order to:
- Allow routing logic to be separate from application logic:
  - This is relevant when multiple services exist behind the same ALB and the paths used to redirect are passed on to the service.
  - Allows CORS to be handled outside application logic which should be useful inside the public API.
- Partition load on the routing service.

We can do this by:
- Adding additional nginx container to current task definitions.
- Define links between containers as appropriate in task definition.
- Describing nginx image (possibly using Packer).

**Comment by alexwlchan** [comment]
Related to #85.

**Comment by kenoir** [comment]
Started https://github.com/wellcometrust/platform-infra/pull/11
